In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df_test = pd.read_csv('train.csv')
df_test.head()

   Property_Id  ... Price_Category
0          381  ...   Semi-Premium
1         1351  ...   Semi-Premium
2         3119  ...        Premium
3         3564  ...   Semi-Premium
4         1518  ...     Affordable

[5 rows x 20 columns]

# New section

In [ ]:
#checking for null values in each column
df_test.isnull().sum()

Property_Id                                0
Title                                      0
Label                                      0
Type                                       0
Location                                   0
Baths                                      0
Area                                       0
Purpose                                    0
Bedroom(s)                                 0
Description                                0
Main Features                              0
Rooms                                      0
Business and Communication                 0
Healthcare Recreational                    0
Nearby Locations and Other Facilities      0
Other Facilities                           0
Popular                                  984
Source                                     0
Time Stamp                                 0
Price_Category                             0
dtype: int64

In [ ]:
df_test.shape

(3082, 20)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3082 entries, 0 to 3081
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Property_Id                            3082 non-null   int64
 1   Title                                  3082 non-null   object
 2   Label                                  3082 non-null   object
 3   Type                                   3082 non-null   object
 4   Location                               3082 non-null   object
 5   Baths                                  3082 non-null   object
 6   Area                                   3082 non-null   object
 7   Purpose                                3082 non-null   object
 8   Bedroom(s)                             3082 non-null   object
 9   Description                            3082 non-null   object
 10  Main Features                          3082 non-null   object
 11  Rooms                                  3082 non-null   object
 12  Business and Communication             3082 non-null   object
 13  Healthcare Recreational                3082 non-null   object
 14  Nearby Locations and Other Facilities  3082 non-null   object
 15  Other Facilities                       3082 non-null   object
 16  Popular                                2098 non-null   object
 17  Source                                 3082 non-null   object
 18  Time Stamp                             3082 non-null   object
 19  Price_Category                         3082 non-null   object
dtypes: int64(1), object(19)
memory usage: 481.7+ KB

In [ ]:
#To ensure uniformity in column names, We removed all spaces at the end(if any existed) and also set names to lowercase
df_test.columns= df_test.columns.str.strip().str.lower() 
df_test.head()

   property_id  ... price_category
0          381  ...   Semi-Premium
1         1351  ...   Semi-Premium
2         3119  ...        Premium
3         3564  ...   Semi-Premium
4         1518  ...     Affordable

[5 rows x 20 columns]

In [ ]:
#Checking for problems and anomalies in all columns

#Decide what to do with these columns
df_test["type"].unique()    #since all have the same type: 'House', we will remove this column 
df_test["purpose"].unique() #since all have the same type: 'For sale', we will remove this column
df_test["source"].unique()# maybe drop this?
#df_test["time stamp"].unique()# maybe drop this?
#df_test["description"].unique() # maybe drop this?
#title, label, description, purpose


#df_test["business and communication"].unique()# maybe drop this?
#df_test["nearby locations and other facilities"].unique() # maybe drop this?
#print(df_test["healthcare recreational"].unique())
#print(df_test["other facilities"].unique())#need to decide what to do about this


#Saifullah 
#df_test["main features"].unique()# maybe drop this?
#df_test["area"].unique()

#need to replace the value '-' with 0 in both these   #DONE

#print(df_test["baths"].unique()   )
#print(df_test["bedroom(s)"].unique() )

#need to convert kanal values to marla and then convert to integer

#Ahmed
#need to split into Seperate categories
#print(df_test["rooms"].unique()) #Split into columns
#df_test["source"].unique() #Split into columns


#have to fix nan values using knn method. We cannot remove nan rows since they are too a large percentage of our total data
#print(df_test["popular"].unique()) 


#print(df_test["price_category"].unique())#this is ok

array(['Lahore-1-10', 'Islamabad-3-8', 'Lahore-1-16', 'Karachi-2-49',
       'Islamabad-3-41', 'Karachi-2-34', 'Islamabad-3-5', 'Lahore-1-17',
       'Islamabad-3-25', 'Karachi-2-3', 'Lahore-1-29', 'Lahore-1-47',
       'Karachi-2-15', 'Karachi-2-39', 'Karachi-2-28', 'Islamabad-3-26',
       'Karachi-2-20', 'Lahore-1-18', 'Islamabad-3-12', 'Lahore-1-4',
       'Islamabad-3-32', 'Lahore-1-35', 'Lahore-1-25', 'Lahore-1-24',
       'Islamabad-3-17', 'Islamabad-3-20', 'Islamabad-3-14',
       'Karachi-2-46', 'Karachi-2-29', 'Karachi-2-33', 'Lahore-1-49',
       'Lahore-1-28', 'Lahore-1-43', 'Lahore-1-32', 'Karachi-2-47',
       'Karachi-2-45', 'Islamabad-3-47', 'Karachi-2-11', 'Lahore-1-42',
       'Karachi-2-36', 'Karachi-2-12', 'Islamabad-3-35', 'Karachi-2-35',
       'Karachi-2-27', 'Lahore-1-6', 'Islamabad-3-40', 'Islamabad-3-11',
       'Karachi-2-37', 'Islamabad-3-46', 'Islamabad-3-2', 'Lahore-1-1',
       'Islamabad-3-38', 'Lahore-1-48', 'Karachi-2-40', 'Islamabad-3-31',
       'Islamabad-3-43', 'Lahore-1-34', 'Lahore-1-39', 'Lahore-1-31',
       'Karachi-2-13', 'Lahore-1-7', 'Karachi-2-43', 'Lahore-1-40',
       'Lahore-1-50', 'Lahore-1-44', 'Islamabad-3-9', 'Lahore-1-41',
       'Islamabad-3-21', 'Lahore-1-15', 'Lahore-1-5', 'Lahore-1-9',
       'Islamabad-3-50', 'Islamabad-3-29', 'Karachi-2-44',
       'Islamabad-3-10', 'Islamabad-3-13', 'Islamabad-3-36',
       'Lahore-1-14', 'Islamabad-3-18', 'Lahore-1-33', 'Islamabad-3-45',
       'Karachi-2-50', 'Lahore-1-12', 'Lahore-1-26', 'Karachi-2-32',
       'Islamabad-3-44', 'Lahore-1-3', 'Karachi-2-2', 'Islamabad-3-30',
       'Islamabad-3-22', 'Karachi-2-42', 'Lahore-1-23', 'Islamabad-3-19',
       'Lahore-1-21', 'Lahore-1-46', 'Karachi-2-31', 'Karachi-2-5',
       'Lahore-1-38', 'Islamabad-3-49', 'Karachi-2-30', 'Karachi-2-38',
       'Karachi-2-24', 'Lahore-1-8', 'Karachi-2-48', 'Lahore-1-13',
       'Karachi-2-25', 'Islamabad-3-7', 'Lahore-1-20', 'Karachi-2-19',
       'Lahore-1-19', 'Lahore-1-2', 'Karachi-2-17', 'Karachi-2-18',
       'Lahore-1-30', 'Karachi-2-23', 'Islamabad-3-3', 'Islamabad-3-39',
       'Islamabad-3-37', 'Islamabad-3-6', 'Lahore-1-22', 'Islamabad-3-42',
       'Islamabad-3-1', 'Islamabad-3-23', 'Lahore-1-27', 'Karachi-2-16',
       'Karachi-2-4', 'Karachi-2-22', 'Karachi-2-1', 'Karachi-2-14',
       'Lahore-1-45', 'Islamabad-3-15', 'Karachi-2-21', 'Islamabad-3-48',
       'Lahore-1-36', 'Islamabad-3-34', 'Karachi-2-41', 'Lahore-1-37',
       'Islamabad-3-33', 'Lahore-1-11', 'Islamabad-3-16',
       'Islamabad-3-24', 'Islamabad-3-4', 'Islamabad-3-27',
       'Karachi-2-26', 'Islamabad-3-28'], dtype=object)

In [ ]:
#need to replace the value '-' with 0 in bath and bedroom columns

df_test["baths"] = df_test["baths"].replace(['-'],[0])
df_test["bedroom(s)"] = df_test["bedroom(s)"].replace(['-'],[0])

#df_test["baths"].unique()  
##df_test["bedroom(s)"].unique()

In [ ]:
#have to fix popular column after all other columns are fixed to ensure accuracy

#In popular column, we cannot remove nan rows since they are too a large percentage of our total data
#We have to fix nan values using knn method. 
#Impute/Replace nan values with placeholder values
#df_test["popular"].unique() 

#from fancyimpute import KNN
#from sklearn.preprocessing import OrdinalEncoder

In [ ]:

#df_test.drop("type", axis=1,inplace=True)
#df_test.drop("purpose", axis=1,inplace=True)
df_test.head()

   property_id  ... price_category
0          381  ...   Semi-Premium
1         1351  ...   Semi-Premium
2         3119  ...        Premium
3         3564  ...   Semi-Premium
4         1518  ...     Affordable

[5 rows x 20 columns]

In [ ]:
def areaRegulator(area_col):
    real_area = []
    for each in area_col:
        each=each.split(' ')
        if 'Kanal' in each:
            real_area.append(float(each[0])*20)
        elif 'Marla' in each:
            real_area.append(float(each[0]))
        else:
            print(each)
    return np.array(real_area,'float64')
        #break
    
res = areaRegulator(df_test['area'])

#print(res)

In [ ]:
def featureExtractor(area_col):
    #real_area = []
    unique_features = {}
    for each in area_col:
        each = each.split(',')
        each = [feature.strip() for feature in each]
        each = [ feature.split(':') for feature in each]
        each = [ [feature.strip().lower() for feature in features] for features in each]
        for features in each:
            if features[0] not in unique_features:
                if len(features) > 1:
                    unique_features[features[0]] = 'int'
                else:
                    unique_features[features[0]] = 'disc'
            elif len(features) > 1 and unique_features[features[0]]=='disc':
                unique_features[features[0]] = 'int'
                #print('whoops')
            elif len(features) > 2:
                print(features)
    if '' in unique_features:
        del unique_features['']
    #print(unique_features)
    #print(len(unique_features))
    return unique_features

def sourceExtractor(source_col):
    sources = {'islamabad':[] , 'lahore':[] , 'karachi':[] }
    counter = 0
    for each in source_col:
        each = each.split('-')
        example ={each[0].lower():1}
        for each_loc in sources:
            if each_loc not in example:
                sources[each_loc].append(0)
            else:
                sources[each_loc].append(1)
        #if counter==10:
        #    break
        #counter+=1
    return sources


def mainExtractor(main_col):
    total_features = featureExtractor(main_col)
    new_features = {each:[] for each in total_features}
    #counter=0
    for each_desc in main_col:
        each_desc = each_desc.split(',')
        each_desc = [ each.strip() for each in each_desc]
        each_desc = [each.split(':') for each in each_desc]
        each_desc = [ [each.strip().lower() for each in features] for features in each_desc]
        example = {}
        for each_feature in each_desc:
            if len(each_feature)>1:
                example[each_feature[0]] = float(each_feature[1].strip())
            else:
                example[each_feature[0]] = 1
        for each_feature in total_features:
            if each_feature not in example:
                new_features[each_feature].append(0)
            else:
                new_features[each_feature].append(example[each_feature])
        #if counter==10:
        #    break
        #counter+=1
    #for each in new_features:
    #    print(each)
    #    print(new_features[each][1])
    return new_features

#mainExtractor(df_test['business and communication'])
res = sourceExtractor(df_test['source'])

In [ ]:
for each in res:
    #print(each,end='   ')
    print(res[each])

[0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1]
[1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]

In [ ]:
df_test.head()

   property_id  ... price_category
0          381  ...   Semi-Premium
1         1351  ...   Semi-Premium
2         3119  ...        Premium
3         3564  ...   Semi-Premium
4         1518  ...     Affordable

[5 rows x 20 columns]

In [ ]:
#def sourceExtractor(source_col):
sources = {'islamabad':[] , 'lahore':[] , 'karachi':[] }
counter = 0
for each in df_test["source"]:
    each = each.split('-')
    example ={each[0].lower():1}
    for each_loc in sources:
        if each_loc not in example:
            sources[each_loc].append(0)
        else:
            sources[each_loc].append(1)
    #if counter==10:
    #    break
    #counter+=1
#print(sources)

cities=pd.DataFrame(sources)
cities

#replace source with cities

      islamabad  lahore  karachi
0             0       1        0
1             1       0        0
2             0       1        0
3             0       0        1
4             1       0        0
...         ...     ...      ...
3077          1       0        0
3078          0       1        0
3079          1       0        0
3080          1       0        0
3081          1       0        0

[3082 rows x 3 columns]

In [ ]:
#Forming Final DataFrame

        #Adding individual cities
Final_Draframe=pd.DataFrame
Final_Draframe=df_test
Final_Draframe=pd.concat([cities, Final_Draframe],axis=1)

        #Fixing area - (Marla/Kanal) issue
b_df=pd.DataFrame(areaRegulator(df_test["area"]))
Final_Draframe=pd.concat([b_df, Final_Draframe],axis=1)
Final_Draframe=Final_Draframe.rename(columns={0: 'area (Marla)'})


        #dropping some useless columns
Final_Draframe.drop("type", axis=1,inplace=True)
Final_Draframe.drop("purpose", axis=1,inplace=True)
Final_Draframe.drop("description", axis=1,inplace=True)
Final_Draframe.drop("title", axis=1,inplace=True)
Final_Draframe.drop("time stamp", axis=1,inplace=True)


        #Splitting business and communication column into seperate columns
c_df=pd.DataFrame(mainExtractor(Final_Draframe["business and communication"]))
#Dropping the following colmns from c_df since only a few houses contained them
#c_df.drop("business center or media room in building", axis=1,inplace=True)
#c_df.drop("conference room in building", axis=1,inplace=True)
#c_df.drop("atm machines", axis=1,inplace=True)
Final_Draframe=pd.concat([c_df, Final_Draframe],axis=1)

        #Splitting nearby locations and other facilities column into seperate columns
d_df=pd.DataFrame(mainExtractor(Final_Draframe["nearby locations and other facilities"]))
Final_Draframe=pd.concat([d_df, Final_Draframe],axis=1)

        #Splitting healthcare recreationals column into seperate columns
e_df=pd.DataFrame(mainExtractor(Final_Draframe["healthcare recreational"]))
Final_Draframe=pd.concat([e_df, Final_Draframe],axis=1)

         #Splitting other facilities column into seperate columns
f_df=pd.DataFrame(mainExtractor(Final_Draframe["other facilities"]))
#Dropping the following colmns from f_df since only a few houses contained them
#f_df.drop("laundry or dry cleaning facility", axis=1,inplace=True)
#f_df.drop("communal/shared kitchen", axis=1,inplace=True)
#f_df.drop("cctv security", axis=1,inplace=True)
#f_df.drop("cafeteria/canteen", axis=1,inplace=True)
Final_Draframe=pd.concat([f_df, Final_Draframe],axis=1)

        #Splitting rooms column into seperate columns
h_df=pd.DataFrame(mainExtractor(Final_Draframe["rooms"]))
#Dropping the following colmns from h_df since dataframe already contains these columns
#h_df.drop("bedrooms", axis=1,inplace=True)
#h_df.drop("bathrooms", axis=1,inplace=True)
Final_Draframe=pd.concat([h_df, Final_Draframe],axis=1)

        #Splitting main features column into seperate columns
g_df=pd.DataFrame(mainExtractor(Final_Draframe["main features"]))
#Dropping the following colmns from g_df since only a few houses contained them
#g_df.drop("lobby in building", axis=1,inplace=True)
#g_df.drop("service elevators in building", axis=1,inplace=True)
#g_df.drop("public parking", axis=1,inplace=True)
#g_df.drop("underground parking", axis=1,inplace=True)
#g_df.drop("elevator or lift", axis=1,inplace=True)
#g_df.drop("built in year", axis=1,inplace=True)
Final_Draframe=pd.concat([g_df, Final_Draframe],axis=1)

        #dropping some more useless columns
Final_Draframe.drop("business and communication", axis=1,inplace=True)
Final_Draframe.drop("healthcare recreational", axis=1,inplace=True)
Final_Draframe.drop("nearby locations and other facilities", axis=1,inplace=True)
Final_Draframe.drop("other facilities", axis=1,inplace=True)
Final_Draframe.drop("main features", axis=1,inplace=True)
Final_Draframe.drop("rooms", axis=1,inplace=True)
Final_Draframe.drop("area", axis=1,inplace=True)
Final_Draframe.drop("baths", axis=1,inplace=True)
Final_Draframe.drop("bedroom(s)", axis=1,inplace=True)

In [ ]:
Final_Draframe.head()

   built in year  parking spaces  ...          source  price_category
0         2018.0             4.0  ...     Lahore-1-10    Semi-Premium
1            0.0             0.0  ...   Islamabad-3-8    Semi-Premium
2            0.0             0.0  ...     Lahore-1-16         Premium
3            0.0             0.0  ...    Karachi-2-49    Semi-Premium
4            0.0             0.0  ...  Islamabad-3-41      Affordable

[5 rows x 67 columns]

In [ ]:
Final_Draframe.shape

(3082, 67)

In [ ]:
Final_Draframe.columns

Index(['built in year', 'parking spaces', 'double glazed windows', 'flooring',
       'electricity backup', 'waste disposal', 'floors', 'furnished',
       'central air conditioning', 'central heating', 'other main features',
       'lobby in building', 'service elevators in building', 'public parking',
       'underground parking', 'elevator or lift', 'bedrooms', 'bathrooms',
       'servant quarters', 'drawing room', 'dining room', 'kitchens',
       'study room', 'prayer room', 'store rooms', 'lounge or sitting room',
       'laundry room', 'powder room', 'gym', 'steam room', 'other rooms',
       'maintenance staff', 'security staff', 'facilities for disabled',
       'laundry or dry cleaning facility', 'communal/shared kitchen',
       'cctv security', 'cafeteria/canteen', 'lawn or garden', 'swimming pool',
       'sauna', 'jacuzzi', 'other healthcare and recreation facilities',
       'nearby schools', 'nearby hospitals', 'nearby shopping malls',
       'nearby restaurants', 'nearby public transport service',
       'distance from airport (kms)', 'other nearby places',
       'broadband internet access', 'satellite or cable tv ready', 'intercom',
       'other business and communication facilities',
       'business center or media room in building',
       'conference room in building', 'atm machines', 'area (Marla)',
       'islamabad', 'lahore', 'karachi', 'property_id', 'label', 'location',
       'popular', 'source', 'price_category'],
      dtype='object')

In [ ]:
#Final inspection of all columns

Final_Draframe.loc[:,'parking spaces':'servant quarters']
Final_Draframe.loc[:,'drawing room':'steam room']
Final_Draframe.loc[:,'other rooms':'nearby hospitals']
Final_Draframe.loc[:,'nearby shopping malls':'area (Marla)']
Final_Draframe.loc[:,'islamabad':'price_category']

      islamabad  lahore  karachi  ...    popular          source price_category
0             0       1        0  ...  super hot     Lahore-1-10   Semi-Premium
1             1       0        0  ...        hot   Islamabad-3-8   Semi-Premium
2             0       1        0  ...  super hot     Lahore-1-16        Premium
3             0       0        1  ...        NaN    Karachi-2-49   Semi-Premium
4             1       0        0  ...        hot  Islamabad-3-41     Affordable
...         ...     ...      ...  ...        ...             ...            ...
3077          1       0        0  ...        NaN  Islamabad-3-29        Premium
3078          0       1        0  ...  super hot     Lahore-1-35     Affordable
3079          1       0        0  ...        NaN  Islamabad-3-36          Cheap
3080          1       0        0  ...  super hot   Islamabad-3-7   Semi-Premium
3081          1       0        0  ...        hot  Islamabad-3-48     Affordable

[3082 rows x 9 columns]

In [ ]:
#Setting property ID as index

Final_Draframe=Final_Draframe.set_index("property_id")
Final_Draframe.head()

             built in year  parking spaces  ...          source  price_category
property_id                                 ...
381                 2018.0             4.0  ...     Lahore-1-10    Semi-Premium
1351                   0.0             0.0  ...   Islamabad-3-8    Semi-Premium
3119                   0.0             0.0  ...     Lahore-1-16         Premium
3564                   0.0             0.0  ...    Karachi-2-49    Semi-Premium
1518                   0.0             0.0  ...  Islamabad-3-41      Affordable

[5 rows x 66 columns]

In [ ]:
        #Splitting label column into seperate columns
i_df=pd.DataFrame(mainExtractor(Final_Draframe["label"]))
i_df.describe()

       bahria town - gulbahar block  ...  darusslam society
count                   3082.000000  ...        3082.000000
mean                       0.004218  ...           0.000324
std                        0.064820  ...           0.018013
min                        0.000000  ...           0.000000
25%                        0.000000  ...           0.000000
50%                        0.000000  ...           0.000000
75%                        0.000000  ...           0.000000
max                        1.000000  ...           1.000000

[8 rows x 624 columns]

In [ ]:
        #Splitting location column into seperate columns
j_df=pd.DataFrame(mainExtractor(Final_Draframe["location"]))
j_df.describe()
#i_df

       bahria town       lahore  ...  gulfishan colony      zamzama
count  3082.000000  3082.000000  ...       3082.000000  3082.000000
mean      0.133355     0.348475  ...          0.000324     0.000324
std       0.340013     0.476565  ...          0.018013     0.018013
min       0.000000     0.000000  ...          0.000000     0.000000
25%       0.000000     0.000000  ...          0.000000     0.000000
50%       0.000000     0.000000  ...          0.000000     0.000000
75%       0.000000     1.000000  ...          0.000000     0.000000
max       1.000000     1.000000  ...          1.000000     1.000000

[8 rows x 172 columns]

In [ ]:
#To ensure uniformity in column names once again, We removed all spaces at the end(if any existed) and also set names to lowercase
Final_Draframe.columns= Final_Draframe.columns.str.strip().str.lower() 

Final_Draframe.head()

             built in year  parking spaces  ...          source  price_category
property_id                                 ...
381                 2018.0             4.0  ...     Lahore-1-10    Semi-Premium
1351                   0.0             0.0  ...   Islamabad-3-8    Semi-Premium
3119                   0.0             0.0  ...     Lahore-1-16         Premium
3564                   0.0             0.0  ...    Karachi-2-49    Semi-Premium
1518                   0.0             0.0  ...  Islamabad-3-41      Affordable

[5 rows x 66 columns]

In [ ]:
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(0,np.nan)
#Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(np.nan,0)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(21017,2017)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(20184,2018)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(20108,2018)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(2109,2019)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(2048,2018)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(1,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(9,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(10,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(15,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(20,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(240,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(300,np.nan)
Final_Draframe["built in year"]=Final_Draframe["built in year"].replace(np.nan,np.mean(Final_Draframe['built in year']))

In [ ]:
Final_Draframe['built in year'].describe()

count    3082.000000
mean     2017.138016
std         2.790365
min      1988.000000
25%      2017.138016
50%      2017.138016
75%      2018.000000
max      2019.000000
Name: built in year, dtype: float64

In [ ]:
Final_Draframe.columns

Index(['built in year', 'parking spaces', 'double glazed windows', 'flooring',
       'electricity backup', 'waste disposal', 'floors', 'furnished',
       'central air conditioning', 'central heating', 'other main features',
       'lobby in building', 'service elevators in building', 'public parking',
       'underground parking', 'elevator or lift', 'bedrooms', 'bathrooms',
       'servant quarters', 'drawing room', 'dining room', 'kitchens',
       'study room', 'prayer room', 'store rooms', 'lounge or sitting room',
       'laundry room', 'powder room', 'gym', 'steam room', 'other rooms',
       'maintenance staff', 'security staff', 'facilities for disabled',
       'laundry or dry cleaning facility', 'communal/shared kitchen',
       'cctv security', 'cafeteria/canteen', 'lawn or garden', 'swimming pool',
       'sauna', 'jacuzzi', 'other healthcare and recreation facilities',
       'nearby schools', 'nearby hospitals', 'nearby shopping malls',
       'nearby restaurants', 'nearby public transport service',
       'distance from airport (kms)', 'other nearby places',
       'broadband internet access', 'satellite or cable tv ready', 'intercom',
       'other business and communication facilities',
       'business center or media room in building',
       'conference room in building', 'atm machines', 'area (marla)',
       'islamabad', 'lahore', 'karachi', 'label', 'location', 'popular',
       'source', 'price_category'],
      dtype='object')

In [ ]:
Final_Draframe.drop("source", axis=1,inplace=True)
Final_Draframe.drop("label", axis=1,inplace=True)
Final_Draframe.drop("popular", axis=1,inplace=True)
Final_Draframe.drop("location", axis=1,inplace=True)

In [ ]:
x_train = pd.DataFrame
x_train = Final_Draframe
#y_train = Final_Draframe['price_category']
#x_train.drop('property id', axis=1, inplace=True)
#x_train.drop('price_category',axis=1, inplace=True)
#x_train.drop("source", axis=1,inplace=True)
#x_train.drop("label", axis=1,inplace=True)
#x_train.drop("popular", axis=1,inplace=True)
#x_train.drop("location", axis=1,inplace=True)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
from sklearn.neural_network import MLPClassifier as classifier
from sklearn.model_selection import GridSearchCV
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

In [ ]:
def tokeniser(labels):
    label_mappings = {}
    counter=0
    total_labels = labels.unique()
    for each in total_labels:
        label_mappings[each] = counter
        counter+=1
    new_labels = []#np.zeros((len(labels),1))
    for each in labels:
        #print(labels[i])
        new_labels.append(label_mappings[each])
    return label_mappings,np.array(new_labels,'int32')


def normaliser(training_data):
    for each in training_data:
        if len(training_data[each].unique()) != 2:
            x = training_data[each]
            x-= np.mean(x)
            x/= np.std(x)
            training_data[each] = x
    return training_data

In [ ]:
x_train_normalised = normaliser(x_train)
label_mappings , y_train = tokeniser(y_train)
y_train_categorical = keras.utils.to_categorical(y_train)

In [ ]:
y_train_categorical[:5]

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [ ]:
lr_init=[0.4,0.1,0.07,0.03,0.01,0.009,0.003,0.001]
layer_sizes=[(64,32,16,8),(128,64,32),(64,32,16),(128,64),(32,32,8),(32,16,8),(32,16),(64),(64, 32),(32),(16,8),(16,8,4)]
parameters={'learning_rate_init':lr_init,'hidden_layer_sizes':layer_sizes}

In [ ]:
clf1 = GridSearchCV(classifier(random_state=1,activation='logistic',solver='sgd',max_iter=6000),parameters)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x_train_normalised,y_train_categorical,test_size=0.2 , random_state=42)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(2465, 61)
(2465, 4)
(617, 61)
(617, 4)

In [ ]:
clf1.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

GridSearchCV(cv=None, error_score=nan,
             estimator=MLPClassifier(activation='logistic', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=6000, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     rand...
                                     tol=0.0001, validation_fraction=0.1,
                                     verbose=False, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'hidden_layer_sizes': [(64, 32, 16, 8), (128, 64, 32),
                                                (64, 32, 16), (128, 64),
                                                (32, 32, 8), (32, 16, 8),
                                                (32, 16), 64, (64, 32), 32,
                                                (16, 8), (16, 8, 4)],
                         'learning_rate_init': [0.4, 0.1, 0.07, 0.03, 0.01,
                                                0.009, 0.003, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_true= np.argmax(y_test, axis=1).reshape((-1,1))
y_real = clf1.predict(x_test)
y_pred=np.argmax(y_real,axis=1)
accuracy = accuracy_score(np.ravel(y_true), np.ravel(y_pred))
perf_metrics =classification_report(y_true,y_pred,output_dict=True)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))